version: '3'
services:
  web:
    image: richandersonio/public:go-example-webserver
    environment:
        - PORT=80
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: richanderson-ecs
        awslogs-region: us-east-1
        awslogs-stream-prefix: web